http:
  port: 8080

authorization:
  jwtSigningKey: helloWorld
  passwordHashSalt: helloWorld1234

postgres:
  host: localhost
  port: 6432
  dbname: helloWorld
  username: helloWorld
  password: helloWorld
  sslMode: disable

redis:
  host: localhost
  port: 7379
  password: ""
  db: 1

minio:
  endpoint: localhost:9002
  accessKeyId: helloWorld
  secretAccessKeyId: helloWorld
